### ISSUE TITLE
scale ratio defaults

### ISSUE THREAD

**Issue by thatch** [bartei/rotary-controller-python#13]
the dialog could tell you it's the resolution in microns, and probably default to 5/1 instead of 1/20 (I assume that's the kind people will buy because it's inexpensive)

**Comment by bartei** [comment]
I'm adding info buttons next to each variable in the setup page to make it easier to configure the display.

**Comment by bartei** [comment]
Changed defaults for the first start of the application so that it makes more sense with common scales.

If you have bad defaults and want to test the application first startup, delete the contents of the settings folder in your installation folder
