### ISSUE TITLE
glitch: zeroing or touching off is considered motion

### ISSUE THREAD

**Issue by thatch** [bartei/rotary-controller-python#14]

**Comment by bartei** [comment]
@thatch The axis follower was intended to work this way, this might be something that we want as a feature? Can you describe how would you like it to work?

**Comment by thatch** [comment]
I initially wrote this to just note that speed display (part of each CoordBar) momentarily displays a silly number when you zero an axis.  After playing with it more, I see the behavior also applies to sync motion, which is probably how you took it?

Looking more at how I'd use that feature, it seems pretty coupled to rotary table use...

For these, I think it 100% makes sense to never lose position sync (keeping track even when it's disabled or tracked axis zero changes):

* rotary indexing (just R, no tracking)
* helical gearcutting (R based on X) -- X might be used as "to go" but you don't want to double-cut when adjusting it

The easiest machine for me to add this to would be lathe leadscrew, where moving suddenly long distances could be dangerous or crash your tool (even if the spindle isn't turning).

* threading (Z based on spindle) -- I'd expect disengaging and re-engaging to either wait for a partial rev or hop by a partial thread (roughly mimicking what the half-nut does)
* electronic compound for tapers (X based on hand-cranked Z) -- zeroing Z probably shouldn't change sync pos, but decoupling and zeroing X might.

**Comment by bartei** [comment]
I think both examples described above deserve a dedicated dialog for the user to follow, so we can provide safeguards on how the repositioning and zeroing of coordinates is handled

**Comment by bartei** [comment]
Fixed the jumping around with the latest version of the software, it requires also an update of the firmware
